#!/bin/bash
#usage : ./check_rds_new myhost WriteIOPS 800
#OK - WriteIOPS=67.22689075630252 |WriteIOPS=67.22689075630252\n
. /var/spool/nagios/plugins/utils.sh

DBINSTANCE=$1
METRIC=$2
MXTHRESHOLD=$3
MNTHRESHOLD=$4
RESULT=""
MON-GET-CMD="/opt/aws/apitools/mon/bin/mon-get-stats"
AWS-CRED-FILE="/opt/aws/credential.conf"

function checkthresh {
    RESULT=${RESULT/.*}
    if [[ $RESULT -gt $MXTHRESHOLD ]]
	then
	warn
    else
	echo "OK - $STAT |$STAT\n"
	exit $STATE_OK
    fi
}
function warn {
    echo "WARNING - WARNING - $METRIC:$RESULT | $METRIC:$RESULT;"
    exit $STATE_WARNING
}

function check_stat {
    if [[ "$METRIC" == "CPUUtilization" ]]
    then
	RESULT=`$MON-GET-CMD $METRIC --period 60 --namespace AWS/RDS --dimensions "DBInstanceIdentifier=$DBINSTANCE" --statistics "Sum" --aws-credential-file=$AWS-CRED-FILE | tail -n 1 | awk '{print $3}'`
    else
	RESULT=`$MON-GET-CMD $METRIC --period 60 --start-time $(date +'%Y-%m-%dT%H:%M' --date='-1 minutes') --end-time $(date +'%Y-%m-%dT%H:%M') --namespace AWS/RDS --dimensions "DBInstanceIdentifier=$DBINSTANCE" --statistics "Sum" --aws-credential-file=$AWS-CRED-FILE | tail -n 1 | awk '{print $3}'`
    fi

    if [[ "$RESULT" == *E* ]]
    then
	RESULT=$(echo $RESULT | awk '{printf "%f", $1}')
    fi
}



check_stat
STAT="$METRIC=${RESULT}"

if [[ "$METRIC" == "WriteIOPS" ]]
    then
    checkthresh

elif [[ "$METRIC" == "ReadIOPS" ]]
    then
    checkthresh

elif [[ "$METRIC" == "ReadThroughput" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "WriteThroughput" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "ReadLatency" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "WriteLatency" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "DatabaseConnections" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "CPUUtilization" ]]
    then
    checkthresh

elif [[ "$METRIC" == "FreeStorageSpace" ]]
    then
    RESULT=${RESULT/.*}
    if [[ $RESULT -lt $MXTHRESHOLD ]]
	then
	warn
    else
	echo "OK - $STAT |$STAT\n"
	exit $STATE_OK
    fi


elif [[ "$METRIC" == "DiskQueueDepth" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "FreeableMemory" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "BinLogDiskUsage" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

elif [[ "$METRIC" == "SwapUsage" ]]
    then
    echo "OK - $STAT |$STAT\n"
    exit $STATE_OK

else
    echo "UNKNOWN - UNKNOWN CHECK"

fi


