#!/usr/bin/perl
# simple check to get dfs used percentage by visiting hadoops dfshealth page
# usage ./check_dfs_space nym-hadoop1 50070
#use lib '/opt/nagios/perl_lib';
use Nagios::Plugin::Functions;
use strict;
use LWP;

my $dfs;
my $host=shift;
my $port = shift;

my $ua = LWP::UserAgent->new;
my $request = HTTP::Request->new(GET => "http://$host:$port/dfshealth.jsp");

my $resp = $ua->request($request); 
my $code = $resp->content;
$_ = $code;
s/<(\/|!)?[-.a-zA-Z0-9]*.*?>//g;
if($_ =~ m/DFS Remaining% :(.*)%/) {
	#print $1;
}

if (( $1 < 40 )) 
{
	#print "Shit\n";
	nagios_exit('CRITICAL',": DFS Remaining Space at: $1 %");
	#print $dfs;
}
else
{
	#print $dfsre;
	nagios_exit('OK',": DFS Remaining Space at: $1 %");
	#print $dfsre;
}
